baseURL = "http://2025.computational-humanities-research/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Computational Humanities Research 2025"
theme = "chr"
publishDir = "docs"

[params]
  customCSS = ["css/custom.css"]
  short = "CHR2025"

[menu]

  [[menu.main]]
     identifier = "cfp"
     name = "CfP"
     url = "/cfp"
     weight = -2000

   [[menu.main]]
     identifier = "news"
     name = "News"
     url = "/news"
     weight = -1850

   # [[menu.main]]
     # identifier = "venue"
     # name = "Venue"
     # url = "/venue"
     # weight = -1750

  [[menu.main]]
     identifier = "organization"
     name = "Organization"
     url = "/organization"
     weight = -1500

  [[menu.main]]
      identifier = "about"
      name = "About"
      url = "https://computational-humanities-research.org"
      weight = -1000


[markup.goldmark.renderer]
unsafe = true
